### ISSUE TITLE
Branches and CI

### ISSUE THREAD

**Issue by dpshelio** [astro-informatics/purify#104]
> I have a question for everyone - I've found out why there's a problem with SOPT/Purify on jenkins. We are building against `master` but we should building against `development`
> So, normally (and that's not a big norm), `master` is treat as the cutting-edge/development branch (that's why is the default, though in our case it's been `development` for a while)
> and say `stable` as the one from where we do releases.
> So, I could change jenkins to build against `development`
> but it would make more sense to me to change our branching conversion as follows:
> - `development` rename it as `master`
> - `master` rename it as `stable`
> - Keep jenkins building `master` as the main build everynigth
> - Create a new build on jenkins which is run `stable` periodically to see whether we need to fix something on releases (because updates on dependencies)
> Would the people be happy with this? The only change would be for people to branch from `master` next feature people want to develop a new thing.
> I could easily change jenkins.... but because the naming between jenkins and github is not 1:1, it can be a bit confusing.

**Comment by Luke-Pratley** [comment]
@dpshelio This is done right?
