### ISSUE TITLE
`make install` won't work

### ISSUE THREAD

**Issue by dpshelio** [astro-informatics/purify#184]
So, `make install` works... however, if you haven't install `sopt` beforehand, when you want to run purify will fail as it won't find libsopt. A workaround is to set `LD_LIBRARY_PATH` to the external path created when build purify:
`LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:/path/where/you/have/purify/build/external/lib`

**Comment by Luke-Pratley** [comment]
That is strange! I thought the lookup should do it?
