### ISSUE TITLE
Update of open-mpi 3.1.3 on homebrew broke our builds

### ISSUE THREAD

**Issue by dpshelio** [astro-informatics/purify#216]
Somehow open-mpi update on brew - [Homebrew/homebrew-core#5dabd](https://github.com/Homebrew/homebrew-core/commit/5dabd32185e66f42a5bb829f2d4996df8953a034) produced some changes on precisions that made the tests to fail.

Using XCode8 and hombrew not as addon.

- `mpi_algo_factory.cc`
```
CHECK( image.isApprox(solution, 1e-6) )
 with expansion:
   false
 with messages:
   Vector<t_complex>::Map(solution.data(), solution.size()).real().head(10) :=
   0.00057167
   0.000327241
   0.000206206
   0.000143916
    7.3595e-05
   1.03113e-05
             0
             0
             0
             0
   Vector<t_complex>::Map(image.data(), image.size()).real().head(10) :=
   0.000570857
   0.000327199
   0.000206297
   0.000143824
   7.29674e-05
   9.62665e-06
             0
             0
             0
             0
   Vector<t_complex>::Map((image / solution).eval().data(), image.size()).real()
   .head(10) := 0.998578
   0.999874
    1.00044
   0.999361
   0.991473
   0.933603
        nan
        nan
        nan
        nan
```
similar for `residual_image`

**Comment by dpshelio** [comment]
Possible fixes:
- Use spack as a way to fix the dependency versions. Caching the spack installation to make it faster each time
 - attempted on #213 and failed as compiling gcc@7 takes longer than 2 hours - Travis limit. (needed to remove clang from the compilers list first).
- Use newer version of xcode with brew as addon
- Use a mix of brew and spack, where spack installs only open-mpi.

**Comment by Luke-Pratley** [comment]
@dpshelio This is fixed right?
