### ISSUE TITLE
Use conan to install dependencies

### ISSUE THREAD

**Issue by tkoskela** [astro-informatics/purify#295]
https://conan.io/

**Comment by tkoskela** [comment]
Following relative success of https://github.com/astro-informatics/sopt/issues/262, this is ready to proceed

**Comment by SJaffa** [comment]
- [x] Create branch off `development`
- [x] Check it compiles and builds
- [x] Set up Conan to install packages that were installed by GreatCmakeCookoff `lookup_packages`
- [x] See what breaks

**Comment by SJaffa** [comment]
The following commands run fine:
```
conan install ..
cmake -DCMAKE_BUILD_TYPE=Release ..
make
```
`make test` takes ages so I killed it, check another time.

But Actions are failing with the `error: ‘stdout_logger_mt’ is not a member of ‘spdlog’` which we fixed before!?! Confused.

**Comment by tkoskela** [comment]
We fixed that in sopt and this is purify, right? I wonder if the same logging code has been copied into purify

**Comment by SJaffa** [comment]
This error is coming from sopt because Purify pulls the main branch. Once the fix is pulled into the main branch of sopt this should go away.
